# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

# Keep explicit hidden imports for modularized sections/services to improve build determinism.
hiddenimports = [
    'ctxsnap.services',
    'ctxsnap.services.snapshot_service',
    'ctxsnap.services.restore_service',
    'ctxsnap.services.backup_service',
    'ctxsnap.services.search_service',
    'ctxsnap.core.security',
    'ctxsnap.core.sync',
    'ctxsnap.core.sync.base',
    'ctxsnap.core.sync.engine',
    'ctxsnap.core.sync.providers',
    'ctxsnap.core.sync.providers.local',
    'ctxsnap.core.sync.providers.cloud_stub',
    'ctxsnap.ui.main_window_sections',
    'ctxsnap.ui.main_window_sections.automation',
    'ctxsnap.ui.main_window_sections.list_view',
    'ctxsnap.ui.main_window_sections.snapshot_crud',
    'ctxsnap.ui.main_window_sections.settings_backup',
    'ctxsnap.ui.main_window_sections.restore_actions',
]

a = Analysis(
    ['ctxsnap_win.py'],
    pathex=['.'],
    binaries=[],
    datas=[('assets/icon.ico', 'assets'), ('README.md', '.'), ('README.en.md', '.')],
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'PySide6.QtWebEngine',
        'PySide6.QtWebEngineCore',
        'PySide6.QtWebEngineWidgets',
        'PySide6.Qt3DCore',
        'PySide6.Qt3DInput',
        'PySide6.Qt3DLogic',
        'PySide6.Qt3DRender',
        'PySide6.Qt3DExtras',
        'PySide6.QtQuick',
        'PySide6.QtQuick3D',
        'PySide6.QtQuickWidgets',
        'PySide6.QtQml',
        'PySide6.QtDesigner',
        'PySide6.QtHelp',
        'PySide6.QtTest',
        'PySide6.QtMultimedia',
        'PySide6.QtMultimediaWidgets',
        'PySide6.QtCharts',
        'PySide6.QtDataVisualization',
        'PySide6.QtPdf',
        'PySide6.QtScxml',
        'PySide6.QtSensors',
        'PySide6.QtSerialPort',
        'PySide6.QtSql',
        'PySide6.QtSvg',
        'PySide6.QtSvgWidgets',
        'PySide6.QtWebChannel',
        'PySide6.QtWebSockets',
        'PySide6.QtBluetooth',
        'PySide6.QtNfc',
        'PySide6.QtLocation',
        'PySide6.QtPositioning',
        'PySide6.QtRemoteObjects',
        'PySide6.QtTextToSpeech',
        'PySide6.QtXml',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='CtxSnap',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/icon.ico'
)
